---
- name: Exploring the template module and jinja expressions
  hosts: planetexpress
  gather_facts: no   # runs the "setup" module on remote hosts

  # these variables are used to build templates
  vars_files:
    - vars/missions.yml

  Tasks:

    - name: Producing mission orders.txt
      template:
        src: missiontemp.whatever
        dest: ~/{{item.mission}}_orders.txt
      loop:
        "{{deliveries}}"

