#!/usr/bin/env python3

# A program to lead you through ADTMC protocol. Patient treatment/instuction will be printed to your screen.

#Misc stuff used

CAT1= 'CAT I: A medical problem exists which may be life threatening (an emergency) requiring the immediate attention of a physician. First aid should be initiated, and ambulance transportation called for if physician is not immediately available. The scope of practice of a TMC or BAS is normally inadequate for these patients.  the goal is to care for these patients in a facility (usually an emergency center) capable of providing advanced cardiac and trauma life support.'

CAT2= 'CAT II: A medical problem exists which may develop into a life-threatening emergency if not evaluated on a priority basis by a physician, PA, or other qualified provider.'

CAT3= 'CAT III: A medical condition exists which requires PA evaluation. Finding will be recorded on DA Form 5181. Data may be obtained by an ADTMC screener, but the medical officer will ultimately make the disposition.'

CAT4= 'CAT IV: A health condition exists for which self-care is appropriate. The instructions and medications to be offered the patient are contained in Self-Care Check out Form. EITHER THE PATIENT OR SCREEENER MAY ELECT TO OVERRULE THIS RECOMMENDATION OF SELF CARE. If recommendation is overruled proceed as CAT III.'

CAT5= 'CAT V: A medical condition exists which will be appropriately evaluated in a specialty or subspecialty clinic. Consultation with either the PA or the supervising physician is required. When an appointment is not available within the time frame specified by the algorithm, the patient will be referred to Level III, PA TODAY.'

Dispostion=''

#Sorethroat Algorithm flowchart.
def Sore_Throat():
    
    ScreenerQuestions= {
    "1":{
        "question": "Is there a history of recent throat or neck trauma?",
        "yes": "2",
        "no":"3" },
    
    "2":{
        "question": "Does the patient have difficulty speaking or swallowing?",
        "yes": "CAT1",
        "no": "4" },
    
    "3":{
        "question": "Can the patient touch his chin to his chest?",
        "yes": "5",
        "no": "4" },

    "4":{
        "question": "Is patients temperature 100°F or higher or is the patient unable to swallow? determine ablility to swallow by oberving the patient",
        "yes": "CAT1",
        "no": "CAT3" },

    "5":{
        "question": "Does the patient have Asymmetric tonsils?",
        "yes": "CAT2",
        "no": "5.5" },

    "5.5":{
        "question": "Does the patient have a temperature of 101°F or higher, pus on tonsils, or swollen tonsils?",
        "yes": "CAT3",
        "no": "6" },
   
    "6":{
        "question": "Can the patient clear both his ears?",
        "yes": "CAT4",
        "no": "Ear_Pain_Discomfort_Drainage()"},
    }    

    
    start= "1"

    while not (start == "CAT1" or start == "CAT2" or start == "CAT3" or start == "CAT4" or start == "CAT5" or start == "Ear_Pain_Discomfort_Drainage()"):
        print(ScreenerQuestions[start]["question"])
        answer= input(">").lower().strip()
        if answer in ["yes","no"]:
            start = ScreenerQuestions[start][answer]
        else:
            print("Please choose yes or no.")

    if start == "CAT1":
        print(f'\n\nPatient Category:\n\n{CAT1}\n\nRoute patient to appropriate triage location.')
    elif start =="CAT2":
        print(f'\n\nPatient Category:\n\n{CAT2}\n\nRoute patient to appropriate triage location.')
    elif start =="CAT3":
        print(f'\n\nPatient Category:\n\n{CAT3}\n\nRoute patient to appropriate triage location.')
    elif start =="CAT4":
        print(f'\n\nPatient Category:\n\n{CAT4}\n\nRoute patient to appropriate triage location.')
    elif start =="CAT5":
        print(f'\n\nPatient Category:\n\n{CAT5}\n\nRoute patient to appropriate triage location.')
    elif start =="Ear_Pain_Discomfort_Drainage()":
        Ear_Pain_Discomfort_Drainage()

    else:
        print("Something is broken :/")


def Ear_Pain_Discomfort_Drainage():

    ScreenerQuestions= {
    "1":{
        "question": "Can the patient touch his chin to his chest?",
        "yes": "3a",
        "no":"2" },

    "2":{
        "question": "Is the patients temperature 100°F or higher or does the patient have a stiff neck?",
        "yes": "CAT2",
        "no": "3b" },

    "3a":{
        "question": "Does the Patient have vertigo?",
        "yes": "CAT2",
        "no": "4" },

    "3b":{
        "question": "Does the Patient have vertigo?",
        "yes": "CAT2",
        "no": "CAT3" },

    "4":{
        "question": "Is the patients temperature 101°F or higer? Do they have decreased hearing and pain? Do they have discomfort with vertigo?",
        "yes": "CAT3",
        "no": "5" },

    "5":{
        "question": "Are the symptoms associated with cold/flu symptoms?",
        "yes": "CAT4",
        "no": "CAT3" },
    }


    start= "1"

    while not (start == "CAT1" or start == "CAT2" or start == "CAT3" or start == "CAT4" or start == "CAT5"):
        print(ScreenerQuestions[start]["question"])
        answer= input(">").lower().strip()
        if answer in ["yes","no"]:
            start = ScreenerQuestions[start][answer]
        else:
            print("Please choose yes or no.")

    if start == "CAT1":
        print(f'\n\nPatient Category:\n\n{CAT1}\n\nRoute patient to appropriate triage location.')
    elif start =="CAT2":
        print(f'\n\nPatient Category:\n\n{CAT2}\n\nRoute patient to appropriate triage location.')
    elif start =="CAT3":
        print(f'\n\nPatient Category:\n\n{CAT3}\n\nRoute patient to appropriate triage location.')
    elif start =="CAT4":
        print(f'\n\nPatient Category:\n\n{CAT4}\n\nRoute patient to appropriate triage location.')
    elif start =="CAT5":
        print(f'\n\nPatient Category:\n\n{CAT5}\n\nRoute patient to appropriate triage location.')

    else:print("Something is broken :/")


def Cough():

    ScreenerQuestions= {
    "1":{
        "question": "Is the patient short of breath while at rest? (determine the answer by observing the patient.)",
        "yes": "CAT2",
        "no":"2" },

    "2":{
        "question": "Is the patient coughing up rusty or blood-streaked sputum or sputum with every cough?",
        "yes": "CAT3",
        "no": "3" },

    "3":{
        "question": "Is the patients temperature 101°F or greater?",
        "yes": "CAT3",
        "no": "CAT4" },
    }


    start= "1"

    while not (start == "CAT1" or start == "CAT2" or start == "CAT3" or start == "CAT4" or start == "CAT5"):
        print(ScreenerQuestions[start]["question"])
        answer= input(">").lower().strip()
        if answer in ["yes","no"]:
            start = ScreenerQuestions[start][answer]
        else:
            print("Please choose yes or no.")

    if start == "CAT1":
        print(f'\n\nPatient Category:\n\n{CAT1}\n\nRoute patient to appropriate triage location.')
    elif start =="CAT2":
        print(f'\n\nPatient Category:\n\n{CAT2}\n\nRoute patient to appropriate triage location.')
    elif start =="CAT3":
        print(f'\n\nPatient Category:\n\n{CAT3}\n\nRoute patient to appropriate triage location.')
    elif start =="CAT4":
        print(f'\n\nPatient Category:\n\n{CAT4}\n\nRoute patient to appropriate triage location.')
    elif start =="CAT5":
        print(f'\n\nPatient Category:\n\n{CAT5}\n\nRoute patient to appropriate triage location.')

    else:
        print("Something is broken :/")


def Sinus_Problems_Pain():

    ScreenerQuestions= {
    "1":{
        "question": "Can the Patient touch his chin to his chest?",
        "yes": "3",
        "no":"2" },

    "2":{
        "question": "Is the patients temperature greater than 100°F?",
        "yes": "CAT2",
        "no": "CAT3" },

    "3":{
        "question": "Is the patient having difficulty answering simple questions or are they disoriented?",
        "yes": "CAT2",
        "no": "4" },

    "4":{
        "question": "Is the patients temperature 101°F or higher?",
        "yes": "CAT3",
        "no": "5" },

    "5":{
        "question": "Does the patient have a rusty, yellow/green colorted, or foul-smelling nasal discharge?",
        "yes": "CAT3",
        "no": "CAT4" },
    }


    start= "1"

    while not (start == "CAT1" or start == "CAT2" or start == "CAT3" or start == "CAT4" or start == "CAT5"):
        print(ScreenerQuestions[start]["question"])
        answer= input(">").lower().strip()
        if answer in ["yes","no"]:
            start = ScreenerQuestions[start][answer]
        else:
            print("Please choose yes or no.")

    if start == "CAT1":
        print(f'\n\nPatient Category:\n\n{CAT1}\n\nRoute patient to appropriate triage location.')
    elif start =="CAT2":
        print(f'\n\nPatient Category:\n\n{CAT2}\n\nRoute patient to appropriate triage location.')
    elif start =="CAT3":
        print(f'\n\nPatient Category:\n\n{CAT3}\n\nRoute patient to appropriate triage location.')
    elif start =="CAT4":
        print(f'\n\nPatient Category:\n\n{CAT4}\n\nRoute patient to appropriate triage location.')
    elif start =="CAT5":
        print(f'\n\nPatient Category:\n\n{CAT5}\n\nRoute patient to appropriate triage location.')

    else:
        print("Something is broken :/")


def Runny_Stuffy_Nose():

    ScreenerQuestions= {
    "1":{
        "question": "Does the patient have rust yellow/greenish, or foul-smelling nasal discharge? (Observe the discharge; do not use the patient's interpretation alone.)?",
        "yes": "CAT3",
        "no":"CAT4" }}

    start= "1"

    while not (start == "CAT1" or start == "CAT2" or start == "CAT3" or start == "CAT4" or start == "CAT5"):
        print(ScreenerQuestions[start]["question"])
        answer= input(">").lower().strip()
        if answer in ["yes","no"]:
            start = ScreenerQuestions[start][answer]
        else:
            print("Please choose yes or no.")

    if start == "CAT1":
        print(f'\n\nPatient Category:\n\n{CAT1}\n\nRoute patient to appropriate triage location.')
    elif start =="CAT2":
        print(f'\n\nPatient Category:\n\n{CAT2}\n\nRoute patient to appropriate triage location.')
    elif start =="CAT3":
        print(f'\n\nPatient Category:\n\n{CAT3}\n\nRoute patient to appropriate triage location.')
    elif start =="CAT4":
        print(f'\n\nPatient Category:\n\n{CAT4}\n\nRoute patient to appropriate triage location.')
    elif start =="CAT5":
        print(f'\n\nPatient Category:\n\n{CAT5}\n\nRoute patient to appropriate triage location.')

    else:
        print("Something is broken :/")


# Starting menu. User chooses flow Sheet to run.
def Complaint_Menu():
    
    print('ADTMC Algorithm Menu\n ')
    Menu=["Sore Throat", "Ear Pain/Discomfort/Drainage", "Cough", "Sinus Problems/Pain", "Runny/Stuffy Nose"]
    Counter = 0

    for Option in Menu:
        Counter += 1
        print(f"{Counter}: {Option} ")
    
    MenuInput = input('\nPlease select the Cheif Complaint for the patients visit by typing the number beside it: ')
    
    if MenuInput == '1':
        MenuChoice= Sore_Throat()
    
    elif MenuInput == '2':
        MenuChoice= Ear_Pain_Discomfort_Drainage()

    elif MenuInput == '3':
        MenuChoice= Cough()
    
    elif MenuInput == '4':
        MenuChoice= Sinus_Problems_Pain()

    elif MenuInput == '5':
        MenuChoice= Runny_Stuffy_Nose()

    else:
        MenuChoice= 'Invalid Input.'


    print(MenuChoice)



Complaint_Menu()
